import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookOpen,
  Boxes,
  Calendar,
  ChevronDown,
  ChevronsLeft,
  CircleCheck,
  CircleDot,
  Clock,
  CodeXml,
  Copy,
  Cpu,
  Database,
  ExternalLink,
  FileText,
  FlaskConical,
  FolderGit2,
  FolderPlus,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitPullRequest,
  Hash,
  HardDrive,
  Hexagon,
  LayoutGrid,
  Link2,
  ListChecks,
  Maximize2,
  MessageSquare,
  MoreVertical,
  Network,
  Paperclip,
  Play,
  Plug,
  Plus,
  RefreshCw,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  SquareKanban,
  Target,
  Trash2,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP = {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookOpen,
  Boxes,
  Calendar,
  ChevronDown,
  ChevronsLeft,
  CircleCheck,
  CircleDot,
  Clock,
  CodeXml,
  Copy,
  Cpu,
  Database,
  ExternalLink,
  FileText,
  FlaskConical,
  FolderGit2,
  FolderPlus,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitPullRequest,
  Hash,
  HardDrive,
  Hexagon,
  LayoutGrid,
  Link2,
  ListChecks,
  Maximize2,
  MessageSquare,
  MoreVertical,
  Network,
  Paperclip,
  Play,
  Plug,
  Plus,
  RefreshCw,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  SquareKanban,
  Target,
  Trash2,
  Workflow,
  Zap,
  Github: GitBranch, // brand icon not in this lucide build; alias to a git glyph
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof MAP;

export function Icon({
  name,
  className,
  size = 16,
  strokeWidth = 2,
  color,
}: {
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
  color?: string;
}) {
  const Cmp = MAP[name as IconName] ?? CircleDot;
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} color={color} aria-hidden />;
}
